### PR TITLE
Fix DiffUtil callback

### PR DESCRIPTION
**Pull request by maxim-yudin**

### CODE REVIEW

**Review by sandeepsharma-kgp — COMMENTED** [review]
It the correct one and should be merged in solution code

**Review by mayokunadeniyi — COMMENTED** [review]
Using Android Studio 4.0 Preview, there was no warning.

`areItemsTheSame()` **should** check if the `oldItem` and `newItem` are the same using their `id` i.e. 
````
return oldItem.id == newItem.id
````
While 
`areContentsTheSame()` **should** check if the contents of the `oldItem` and `newItem` are the same by using the `equals` property of the item data class i.e.
````
return oldItem == newItem
````

**Review by sandeepsharma-kgp — APPROVED** [review]

**Comment by SudKul** [comment]
Thanks, @maxim-yudin

**Comment by cutiko** [comment]
I was taking a look at something else and found this, and I think this can potentially not be the right solution:

```
val sleep1 =  SleepNight(sleepQuality = 4)
val sleep2 = sleep1.copy(sleepQuality = -26)

val dataItem1 = DataItem. SleepNightItem(sleep1)
val dataItem2 = DataItem. SleepNightItem(sleep2)
```

Since in the above case, both have the same id, `areContentTheSame` will be `true` but is not because the `sleepQuality` is different.

**Pull request merged**
